add pclinuxos

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -68,6 +68,12 @@ case $ID in
             wxwidgets-gtk3 hamlib alsa-lib libao libsndfile python-virtualenv python-numpy manjaro-pulse gsm" \
             || { echo "Deps install failed - try again later"; exit 1; }
     ;;
+    pclinuxos)
+    echo "Enter the root password to install some initially needed dependencies"
+    su -c "apt install --no-install-recommends git cmake wxGTK3-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel alsa-lib-devel \
+           libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-devel hamlib-utils" \
+           || { echo "Deps install failed - try again later"; exit 1; }
+    ;;
     *)
     echo "Sorry I don't have packaging information for $PRETTY_NAME yet."
     echo "Please create an issue with details of your system."
