Add openSUSE Tumbleweed (issue #4).

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -41,8 +41,15 @@ case $ID in
     mageia)
     echo "Enter the root password to install some initially needed dependencies"
     su -c "urpmi git cmake wxGTK3-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel alsa-lib-devel \
-           libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-devel hamlib-utils python3 python3-devel \
-           python3" || { echo "Deps install failed - try again later"; exit 1; }
+           libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-devel hamlib-utils python3 python3-devel" \
+           || { echo "Deps install failed - try again later"; exit 1; }
+    ;;
+    opensuse-tumbleweed)
+    echo "Enter the root password to install some initially needed dependencies"
+    sudo zypper --non-interactive in --no-recommends cmake patch automake autoconf libtool wxGTK3-devel libsamplerate-devel \
+            libsndfile-devel speexdsp-devel alsa-lib-devel libao-devel libgsm-devel gcc-c++ sox python3-virtualenv \
+            pulseaudio-devel python3 python3-devel python3 \
+            || { echo "Deps install failed - try again later"; exit 1; }
     ;;
     linuxmint)
     echo "Enter the root password to install some initially needed dependencies"
