Initial changes for cport

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -23,13 +23,13 @@ user="$(logname 2>/dev/null || echo "$USER")"
 uname -m | grep -q "64" || { echo "ERROR: A 64bit system is needed"; exit 1; }
 
 # Set run directory
-RUN_DIR="/home/$user/freedv-rade-build"
+RUN_DIR="/home/$user/freedv-rade-cbuild"
 echo "Current dir = $(pwd)"
 echo "Changing to RUN_DIR"
 cd "$RUN_DIR" || { echo "Switch to RUN_DIR failed"; exit 1; }
 
 # Set full path to log
-LOGFILE="$RUN_DIR/freedv-rade-build.log"
+LOGFILE="$RUN_DIR/freedv-rade-cbuild.log"
 
 # Check not already running
 echo "Checking for another instance"
@@ -92,7 +92,7 @@ touch "${basedir}"/test_for_perms > /dev/null 2>&1 || { echo -e "Target folder $
 rm -f "${basedir}"/test_for_perms
 
 # Set default build dir name
-builddir=freedv-rade
+builddir=freedv-radec
 
 # Find out where we are
 . /etc/os-release
@@ -143,7 +143,7 @@ case $ID in
     MGA_ID=$(echo "$VERSION_ID"|cut -d. -f1)
     if (( MGA_ID > 9 )); then
             run_as_root "urpmi --auto --no-recommends git cmake wxGTK3-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel alsa-lib-devel \
-            libao-devel gsm-devel gcc-c++ automake sox python3-virtualenv pulseaudio-devel hamlib-utils python3 python3-devel \
+            libao-devel gsm-devel gcc-c++ automake sox  pulseaudio-devel hamlib-utils \
             fonts-ttf-google-noto-emoji-color" || { echo "Deps install failed"; exit 1; }
     else
             run_as_root "urpmi --auto --no-recommends git cmake wxGTK3-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel alsa-lib-devel \
@@ -368,35 +368,35 @@ git clone --progress https://github.com/drowe67/freedv-gui.git || { echo "ERROR:
 cd "${basedir}/${builddir}/freedv-gui" || { echo "ERROR: cd to freedv-gui failed"; exit 1; }
 
 # Create a python virtual environment with access to system python modules
-if [[ $ID == "debug" ]] || [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]] || [[ $ID == "ubuntu" ]] || [[ $ID == "debian" ]] || [[ $ID = "pclinuxos" ]]; then
-    python3 -m venv rade-venv --system-site-packages || { echo "ERROR: create venv failed"; exit 1; }
-else
-# Exclude system modules
-    python3 -m venv rade-venv || { echo "ERROR: create venv failed"; exit 1; }
-fi
+#if [[ $ID == "debug" ]] || [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]] || [[ $ID == "ubuntu" ]] || [[ $ID == "debian" ]] || [[ $ID = "pclinuxos" ]]; then
+#    python3 -m venv rade-venv --system-site-packages || { echo "ERROR: create venv failed"; exit 1; }
+#else
+## Exclude system modules
+#    python3 -m venv rade-venv || { echo "ERROR: create venv failed"; exit 1; }
+#fi
 
 # Activate it
-. ./rade-venv/bin/activate || { echo "ERROR: activate venv failed"; exit 1; }
+#. ./rade-venv/bin/activate || { echo "ERROR: activate venv failed"; exit 1; }
 
 # Clear cache in venv
-pip3 cache purge
-pip3 install --upgrade pip || echo "WARNING: pip upgrade failed"
+#pip3 cache purge
+#pip3 install --upgrade pip || echo "WARNING: pip upgrade failed"
 
 # Install some python dependencies using pip
-pip3 install torch torchaudio --index-url https://download.pytorch.org/whl/cpu || { echo "torch pip install failed"; exit 1; }
+#pip3 install torch torchaudio --index-url https://download.pytorch.org/whl/cpu || { echo "torch pip install failed"; exit 1; }
 
-pip3 install matplotlib || { echo "ERROR: matplotlib pip install failed"; exit 1; }
+#pip3 install matplotlib || { echo "ERROR: matplotlib pip install failed"; exit 1; }
 
-if [[ $ID == "mageia" ]] || [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]] || [[ $ID == "ubuntu" ]] || [[ $ID == "debian" ]]; then
-pip3 install NumPy || { echo "ERROR: numpy pip install failed"; exit 1; }
-fi
+#if [[ $ID == "mageia" ]] || [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]] || [[ $ID == "ubuntu" ]] || [[ $ID == "debian" ]]; then
+#pip3 install NumPy || { echo "ERROR: numpy pip install failed"; exit 1; }
+#fi
 
 # Testing patches for upstream script
 #sed -i 's: -j$(nproc): -j4:' build_linux.sh
 #patch -p1 < ../../freedv-rade-build/cores.patch && echo "cores.patch applied"
 
 # Run the freedv build script
-./build_linux.sh || { echo "ERROR: Build failed for some reason, check for errors above and run again later."; deactivate; exit 1; }
+./build_linux.sh || { echo "ERROR: Build failed for some reason, check for errors above and run again later."; exit 1; }
 
 # Move back into build_linux
 cd "${basedir}/${builddir}/freedv-gui/build_linux" || { echo "ERROR: cd ${basedir}/${builddir}/freedv-gui/build_linux failed"; exit 1; }
@@ -405,16 +405,16 @@ cd "${basedir}/${builddir}/freedv-gui/build_linux" || { echo "ERROR: cd ${basedi
 ln -s "$(pwd)"/rade_src/model19_check3 model19_check3 || { echo "Failed to create symlink"; exit 1; }
 
 # Deactivate venv
-deactivate || echo "WARNING:Issue deactivating venv"
+#deactivate || echo "WARNING:Issue deactivating venv"
 
 # Make start script
-~/freedv-rade-build/mk-start "${basedir}/${builddir}" || echo "WARNING: freedv-start script was not created (maybe exists?)"
+#~/freedv-rade-build/mk-start "${basedir}/${builddir}" || echo "WARNING: freedv-start script was not created (maybe exists?)"
 
 # Make destop file
-~/freedv-rade-build/mk-desktop || echo "WARNING: freedv desktop file was not created (maybe already exists?)"
+#~/freedv-rade-build/mk-desktop || echo "WARNING: freedv desktop file was not created (maybe already exists?)"
 
 # Make Update desktop file
-~/freedv-rade-build/mk-updt-desktop || echo "WARNING: Update-RADE desktop file was not created (maybe already exists?)"
+#~/freedv-rade-build/mk-updt-desktop || echo "WARNING: Update-RADE desktop file was not created (maybe already exists?)"
 
 cd || exit 1
 echo -e "\n\n########### Build is complete \o/ ############\n\nYou can run it from your home folder using:\n\n \
