replace all USER with user

diff --git a/freedv-rade-update b/freedv-rade-update
--- a/freedv-rade-update
+++ b/freedv-rade-update
@@ -4,6 +4,9 @@
 #   Remove old log
     rm -f ~/freedv-rade-build/freedv-rade-update.log || { echo "Failed to remove old log"; exit 1; }
 
+# Get user
+user="$(logname 2>/dev/null || echo "$USER")"
+
 # Start logging
     cat /etc/os-release > ~/freedv-rade-build/freedv-rade-update.log
     exec > >(tee -a ~/freedv-rade-build/freedv-rade-update.log)
@@ -15,11 +18,11 @@ prbranch=""
 pname=""
 cname=""
 
-# Get path of base dir in use, defaults to /home/$USER
-if cat /home/${USER}/freedv-rade-build/freedv-rade-build.cfg |grep -v '^[#]'|grep -q "basedir="; then
-    basedir=$(cat /home/${USER}/freedv-rade-build/freedv-rade-build.cfg|grep -v '^[#]'|grep 'basedir='|cut -d= -f2)
+# Get path of base dir in use, defaults to /home/$user
+if cat /home/${user}/freedv-rade-build/freedv-rade-build.cfg |grep -v '^[#]'|grep -q "basedir="; then
+    basedir=$(cat /home/${user}/freedv-rade-build/freedv-rade-build.cfg|grep -v '^[#]'|grep 'basedir='|cut -d= -f2)
 else
-    basedir=/home/$USER
+    basedir=/home/$user
 fi
 
 confirm() {
@@ -82,7 +85,7 @@ git pull
 
 # Apply a patch if there is one
 if (( ${#pname} > 0 )); then
-    if ! patch -p1 < /home/${USER}/freedv-rade-build/$pname; then
+    if ! patch -p1 < /home/${user}/freedv-rade-build/$pname; then
     echo $(pwd)
         echo "Patch failed to apply.  pwd= $(pwd)"
         exit 1
@@ -119,7 +122,7 @@ branch="$(git status|grep 'On branch')"
 echo "Wait a moment..."
 
 # Check we are not root
-((UID)) || { echo "ERROR: You must NOT be root user to run $0, use CTRL/d to become $USER"; exit 1; }
+((UID)) || { echo "ERROR: You must NOT be root user to run $0, use CTRL/d to become $user"; exit 1; }
 
 # Check we have internet and DNS
 ping -c3 google.com > /dev/null || { echo "ERROR: Failed to find internet connection or DNS"; exit 1; }
@@ -204,7 +207,7 @@ fi
     (( ${#prbranch} == 0 )) && prbranch="$default"
 
 if (( fastupdt == 1 )) && confirm "\n\nAdd a patch?" "[N/y]" "yY" "nN"; then
-    echo -e  "\n NOTE: Patch file must be in /home/$USER/freedv-rade/build/ folder"
+    echo -e  "\n NOTE: Patch file must be in /home/$user/freedv-rade/build/ folder"
     read -r -p "Enter the patch name:" pname
 fi
 
@@ -213,7 +216,7 @@ if (( fastupdt == 1 )) && confirm "\n\nUse a specific commit?" "[N/y]" "yY" "nN"
 fi
 
 # Check patch exists
-(( ${#pname} > 0 )) && [[ -z /home/$USER/freedv-rade-build/$pname ]] && { echo "ERROR: Non existant or invalid patch name"; exit 1; }
+(( ${#pname} > 0 )) && [[ -z /home/$user/freedv-rade-build/$pname ]] && { echo "ERROR: Non existant or invalid patch name"; exit 1; }
 
 
 if ( (( fastupdt == 1 )) || (( update == 1 )) || (( backup = 1 )) ) && (( desktop != 1 )) && (( bak != 1 )) && (( restore != 1 )) && (( switch != 1 )); then
