quote some vars

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -24,25 +24,25 @@ uname -m | grep -q "64" || { echo "ERROR: A 64bit system is needed"; exit 1; }
 
 # Get/set path of base dir to use, defaults to /home/$user
 if [[ -f /home/${user}/.freedv-rade-build.cfg ]]; then
-    if cat /home/${user}/.freedv-rade-build.cfg|grep -v '^[#]'|grep -q "basedir="; then
-        basedir=$(cat /home/${user}/.freedv-rade-build.cfg|grep -v '^[#]'|grep 'basedir='|cut -d= -f2)
+    if cat /home/"${user}"/.freedv-rade-build.cfg|grep -v '^[#]'|grep -q "basedir="; then
+        basedir=$(cat /home/"${user}"/.freedv-rade-build.cfg|grep -v '^[#]'|grep 'basedir='|cut -d= -f2)
     else
         basedir=/home/$user
     fi
 else
-    echo "basedir=/home/$user" > /home/${user}/.freedv-rade-build.cfg
+    echo "basedir=/home/$user" > /home/"${user}"/.freedv-rade-build.cfg
     basedir=/home/$user
 fi
 
 # Check permissions on target dir
-touch ${basedir}/test_for_perms > /dev/null 2>&1 || { echo -e "Target folder $basedir is not writeable by $user\n check permissions on this directory it may need ownership changing.\n"; exit 1; }
-rm -f ${basedir}/test_for_perms
+touch "${basedir}"/test_for_perms > /dev/null 2>&1 || { echo -e "Target folder $basedir is not writeable by $user\n check permissions on this directory it may need ownership changing.\n"; exit 1; }
+rm -f "${basedir}"/test_for_perms
 
 # Set default build dir name
 builddir=freedv-rade
 
 # Check we have space
-(( $(df -hBG --output=avail $basedir |tr '\n' ' '|tr -s ' '|xargs|cut -d ' ' -f2|cut -dG -f1) > 3 )) || { echo "ERROR: You will need more than 3GB of free disk space in $basedir"; exit 1; }
+(( $(df -hBG --output=avail "$basedir" |tr '\n' ' '|tr -s ' '|xargs|cut -d ' ' -f2|cut -dG -f1) > 3 )) || { echo "ERROR: You will need more than 3GB of free disk space in $basedir"; exit 1; }
 
 # Check we have internet and DNS
 ping -c3 google.com > /dev/null || { echo "ERROR: Failed to find internet connection or DNS"; exit 1; }
@@ -94,7 +94,7 @@ echo "Enter the root password if requested to install some initially needed depe
 case $ID in
     mageia)
     groups_to_add+=(dialout)
-    MGA_ID=$(echo $VERSION_ID|cut -d. -f1)
+    MGA_ID=$(echo "$VERSION_ID"|cut -d. -f1)
     if (( MGA_ID > 9 )); then
             run_as_root "urpmi --auto --no-recommends git cmake wxGTK3-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel alsa-lib-devel \
             libao-devel gsm-devel gcc-c++ automake sox python3-virtualenv pulseaudio-devel hamlib-utils python3 python3-devel \
@@ -115,7 +115,7 @@ case $ID in
     ;;
     linuxmint)
     groups_to_add+=(dialout plugdev)
-    MINT_ID=$(echo $VERSION_ID|cut -d. -f1)
+    MINT_ID=$(echo "$VERSION_ID"|cut -d. -f1)
     if (( MINT_ID >= 22 )); then
             run_as_root "apt install -y --no-install-recommends libspeexdsp-dev libsamplerate0-dev sox git libwxgtk3.2-dev libhamlib-dev \
             libasound2-dev libao-dev libgsm1-dev libsndfile1-dev cmake module-assistant build-essential python3-venv libpulse-dev \
@@ -132,7 +132,7 @@ case $ID in
     ;;
     fedora)
     groups_to_add+=(dialout)
-        FC_ID=$(echo $VERSION_ID|cut -d. -f1)
+        FC_ID=$(echo "$VERSION_ID"|cut -d. -f1)
         if (( FC_ID == 42 )); then
             run_as_root "dnf5 install--setopt=install_weak_deps=False @development-tools git cmake wxGTK-devel libsamplerate-devel libsndfile-devel speexdsp-devel \
             hamlib-devel hamlib alsa-lib-devel libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-libs-devel libtool \
@@ -149,7 +149,7 @@ case $ID in
     ;;
     ubuntu)
     groups_to_add+=(dialout plugdev)
-        UBUNTU_ID=$(echo $VERSION_ID|cut -d. -f1)
+        UBUNTU_ID=$(echo "$VERSION_ID"|cut -d. -f1)
             run_as_root "apt update"
         if (( UBUNTU_ID >= 24 )); then
             run_as_root "apt install -y --no-install-recommends libwxgtk3.2-dev python3-numpy-dev python3-venv libspeexdsp-dev libsamplerate0-dev sox git libhamlib-dev \
@@ -167,7 +167,7 @@ case $ID in
     ;;
     debian)
     groups_to_add+=(dialout plugdev)
-    DEBIAN_ID=$(echo $VERSION_ID|cut -d. -f1)
+    DEBIAN_ID=$(echo "$VERSION_ID"|cut -d. -f1)
         if (( DEBIAN_ID >= 12 )); then
             run_as_root "apt install libspeexdsp-dev libsamplerate0-dev sox git libwxgtk3.2-dev libhamlib-dev libasound2-dev libao-dev \
                 libgsm1-dev libsndfile1-dev cmake module-assistant build-essential python3-venv libpulse-dev autoconf libtool \
@@ -255,20 +255,20 @@ for group in "${groups_to_add[@]}"; do
 done
 
 # Create a build directory
-mkdir -p ${basedir}/${builddir} || { echo "ERROR: mkdir ${basedir}/${builddir} failed"; exit 1; }
+mkdir -p "${basedir}/${builddir}" || { echo "ERROR: mkdir ${basedir}/${builddir} failed"; exit 1; }
 
 # Move into build dir
-cd ${basedir}/${builddir} || { echo "ERROR: cd to ${basedir}/${builddir} failed"; exit 1; }
+cd "${basedir}/${builddir}" || { echo "ERROR: cd to ${basedir}/${builddir} failed"; exit 1; }
 
 # Delete freedv-gui directory
-rm -rf ${basedir}/${builddir}/freedv-gui || { echo "ERROR: removing old freedv-gui dir"; exit 1; }
+rm -rf "${basedir}/${builddir}/freedv-gui" || { echo "ERROR: removing old freedv-gui dir"; exit 1; }
 
 # Get the latest freedv sources from github
 echo Cloning freedv github repository...
 git clone https://github.com/drowe67/freedv-gui.git || { echo "ERROR: git clone failed"; exit 1; }
 
 # Move into source code directory
-cd ${basedir}/${builddir}/freedv-gui || { echo "ERROR: cd to freedv-gui failed"; exit 1; }
+cd "${basedir}/${builddir}/freedv-gui" || { echo "ERROR: cd to freedv-gui failed"; exit 1; }
 
 # Create a python virtual environment with access to system python modules
 if [[ $ID == "debug" ]] || [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]] || [[ $ID == "ubuntu" ]] || [[ $ID == "debian" ]] || [[ $ID = "pclinuxos" ]]; then
@@ -302,7 +302,7 @@ fi
 ./build_linux.sh || { echo "ERROR: Build failed for some reason, check for errors above and run again later."; deactivate; exit 1; }
 
 # Move back into build_linux
-cd ${basedir}/${builddir}/freedv-gui/build_linux || { echo "ERROR: cd ${basedir}/${builddir}/freedv-gui/build_linux failed"; exit 1; }
+cd "${basedir}/${builddir}/freedv-gui/build_linux" || { echo "ERROR: cd ${basedir}/${builddir}/freedv-gui/build_linux failed"; exit 1; }
 
 # Create symlink 
 ln -s "$(pwd)"/rade_src/model19_check3 model19_check3 || { echo "Failed to create symlink"; exit 1; }
@@ -311,7 +311,7 @@ ln -s "$(pwd)"/rade_src/model19_check3 model19_check3 || { echo "Failed to creat
 deactivate || echo "WARNING:Issue deactivating venv"
 
 # Make start script
-~/freedv-rade-build/mk-start ${basedir}/${builddir} || echo "WARNING: freedv-start script was not created (maybe exists?)"
+~/freedv-rade-build/mk-start "${basedir}/${builddir}" || echo "WARNING: freedv-start script was not created (maybe exists?)"
 
 # Make destop file
 ~/freedv-rade-build/mk-desktop || echo "WARNING: freedv desktop file was not created (maybe already exists?)"
@@ -319,7 +319,7 @@ deactivate || echo "WARNING:Issue deactivating venv"
 # Make Update desktop file
 ~/freedv-rade-build/mk-updt-desktop || echo "WARNING: Update-RADE desktop file was not created (maybe already exists?)"
 
-cd
+cd || exit 1
 echo -e "\n\n########### Build is complete \o/ ############\n\nYou can run it from your home folder using:\n\n \
       ./freedv-start [-f configfile]\n\n  OR  use the FreeDV-RADE desktop icon.\n\n"
 
