remove libsioclient dep from Mageia

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -25,7 +25,7 @@ case $ID in
     echo "Enter the root password to install some initially needed dependencies"
     su -c "urpmi git cmake wxGTK3-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel alsa-lib-devel \
            libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-devel hamlib-utils python3 python3-devel \
-           libsioclient-devel python3" || { echo "Deps install failed - try again later"; exit 1; }
+           python3" || { echo "Deps install failed - try again later"; exit 1; }
     ;;
     linuxmint)
     echo "Enter the root password to install some initially needed dependencies"
