fix fedora 41 build, add rigctld start/stop to freedv-start script, edit README.md

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -38,8 +38,9 @@ case $ID in
     fedora)
     echo "Enter the root password to install some initially needed dependencies"
     sudo dnf group install development-tools
-    sudo dnf install git cmake wxGTK-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel \
-         alsa-lib-devel libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-libs-devel libtool \
+    sudo dnf install --setopt=install_weak_deps=False git cmake wxGTK-devel libsamplerate-devel libsndfile-devel speexdsp-devel \
+    hamlib-devel hamlib alsa-lib-devel libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-libs-devel libtool \
+         python3-torchaudio python3-torch python3-devel \
            || { echo "Deps install failed - try again later"; exit 1; }
     ;;
     ubuntu)
@@ -80,23 +81,26 @@ cd freedv-gui || { echo "cd to freedv-gui failed"; exit 1; }
 # Change to the RADE branch
 git checkout v2.0-dev || { echo "checkout v2.0 failed"; exit 1; }
 
-# Create a python virtual environment
-if [[ $ID == "linuxmint" ]]; then
+# Create a python virtual environment with access to system python modules
+if [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]]; then
     python3 -m venv rade-venv --system-site-packages || { echo "create venv failed"; exit 1; }
 else
+# Exclude system modules
     python3 -m venv rade-venv || { echo "create venv failed"; exit 1; }
 fi
 
 # Activate it
 . ./rade-venv/bin/activate || { echo "activate venv failed"; exit 1; }
 
-# Clear cache
+# Clear cache in venv
 pip cache purge
 
 # Install some python dependencies using pip
-pip3 install torch torchaudio --index-url https://download.pytorch.org/whl/cpu || { echo "torch pip install failed"; exit 1; } 
+if [[ $ID != "fedora" ]]; then
+pip3 install torch torchaudio --index-url https://download.pytorch.org/whl/cpu || { echo "torch pip install failed"; exit 1; }
+fi
 pip3 install matplotlib || { echo "matplotlib pip install failed"; exit 1; }
-if [[ $ID == "linuxmint" ]]; then
+if [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]]; then
 pip3 install NumPy || { echo "numpy pip install failed"; exit 1; }
 fi
 # Run the freedv build script
@@ -110,7 +114,13 @@ cat > freedv-start <<EOF
 # Specify a config file to use (optional) default is ~/.freedv
 # e.g. freedv-start -f myfreedv.conf
 ####################################
-
+# Edit and uncomment the following line with your radio code (-m) and USB port (-r) to start rigctld at freedv launch.
+# Mine below is for the TS-450S, yours will be different probably without the --set-conf.....
+#
+# rigctld -m 2003 -r /dev/ttyUSB0 -T 0.0.0.0 -t 4532 --set-conf=serial_handshake=None
+#
+# You will then in freedv set the radio model to 'Hamlib NET rigctl' in the 'CAT and PTT config' and the 'Serial Device' to 'localhost:4532'
+#
 cd /home/\$USER/$builddir/freedv-gui
 . ./rade-venv/bin/activate
 cd build_linux
@@ -135,3 +145,5 @@ echo -e "\n########### Build is complete \o/ ############\nYou can run it from y
 # Return home
 cd
 
+# Uncomment
+#pkill rigctld
