fix all numeric versions

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -62,7 +62,7 @@ case $ID in
     ;;
     linuxmint)
     echo "Enter the root password to install some initially needed dependencies"
-    if [[ "$VERSION_ID" -lt "22" ]]; then
+    if (( VERSION_ID < 22 )); then
             sudo apt install libspeexdsp-dev libsamplerate0-dev sox git libwxgtk3.0-dev libhamlib-dev libasound2-dev libao-dev \
             libgsm1-dev libsndfile1-dev cmake module-assistant build-essential python3.12-venv libpulse-dev autoconf libtool \
             python3-numpy-dev python3 python3-dev libhamlib-utils fonts-noto-color-emoji \
@@ -76,13 +76,13 @@ case $ID in
     ;;
     fedora)
     echo "Enter the root password to install some initially needed dependencies"
-        if [[ "$VERSION_ID" -ge "42" ]]; then
+        if (( VERSION_ID >= 42 )); then
             sudo dnf5 install @development-tools
             sudo dnf5 install git cmake wxGTK-devel libsamplerate-devel libsndfile-devel speexdsp-devel \
             hamlib-devel hamlib alsa-lib-devel libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-libs-devel libtool \
             python3-devel google-noto-emoji-color-fonts \
             || { echo "Deps install failed - try again later"; exit 1; }
-        elif [[ "$VERSION_ID" -le "41" ]]; then
+        else
             sudo dnf group install development-tools
             sudo dnf install --setopt=install_weak_deps=False git cmake wxGTK-devel libsamplerate-devel libsndfile-devel speexdsp-devel \
             hamlib-devel hamlib alsa-lib-devel libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-libs-devel libtool \
@@ -92,15 +92,14 @@ case $ID in
     ;;
     ubuntu)
     echo "Enter the root password to install some initially needed dependencies"
-        if [[ "$VERSION_ID" == "24.04" ]]; then
-            sudo apt install libwxgtk3.2-dev python3-numpy-dev python3.12-venv || { echo "Deps install failed - try again later"; exit 1; }
-        elif [[ "$VERSION_ID" == "22.04" ]]; then
-            sudo apt install libwxgtk3.0-gtk3-dev python3-numpy python3.10-venv || { echo "Deps install failed - try again later"; exit 1; }
+        UBUNTU_ID=$(echo $VERSION_ID|tr -d '.')
+        if (( UBUNTU_ID >= 2404 )); then
+            sudo apt install libwxgtk3.2-dev python3-numpy-dev python3.12-venv libspeexdsp-dev libsamplerate0-dev sox git libhamlib-dev \ libasound2-dev libao-dev libgsm1-dev libsndfile1-dev cmake module-assistant build-essential libpulse-dev autoconf libtool \
+            python3 python3-dev libhamlib-utils fonts-noto-color-emoji || { echo "Deps install failed - try again later"; exit 1; }
+        else
+            sudo apt install libwxgtk3.0-gtk3-dev python3-numpy python3.10-venv libspeexdsp-dev libsamplerate0-dev sox git libhamlib-dev \ libasound2-dev libao-dev libgsm1-dev libsndfile1-dev cmake module-assistant build-essential libpulse-dev autoconf libtool \
+            python3 python3-dev libhamlib-utils fonts-noto-color-emoji || { echo "Deps install failed - try again later"; exit 1; }
         fi
-            sudo apt install libspeexdsp-dev libsamplerate0-dev sox git libhamlib-dev libasound2-dev libao-dev \
-                libgsm1-dev libsndfile1-dev cmake module-assistant build-essential libpulse-dev autoconf libtool \
-                python3 python3-dev libhamlib-utils fonts-noto-color-emoji \
-                || { echo "Deps install failed - try again later"; exit 1; }
     ;;
     debian)
     echo "Enter the root password to install some initially needed dependencies"
