Testing changes for Mageia

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -1,19 +1,19 @@
 #!/bin/bash
 # This script tries to install the pre-release freedv-v2.00 from github on various linux distributions
 # Check we are not root
-((UID)) || { echo "You must NOT run $0 as root - aborting!"; exit 0; }
+((UID)) || { echo "ERROR: You must NOT run $0 as root - aborting!"; exit 0; }
 
 # Check that this is a 64bit machine
-uname -m | grep -q "64" || { echo "Error: A 64bit system is needed"; exit 1; }
+uname -m | grep -q "64" || { echo "ERROR: A 64bit system is needed"; exit 1; }
 
 # Path of base dir to use
 builddir=/home/$USER/freedv-rade
 
 # Check we have space
-(( $(df -hBG --output=avail /home |tr '\n' ' '|tr -s ' '|cut -d ' ' -f2|cut -dG -f1) > 3 )) || { echo "You will need more than 3GB of free disk space in $HOME"; exit 1; }
+(( $(df -hBG --output=avail /home |tr '\n' ' '|tr -s ' '|cut -d ' ' -f2|cut -dG -f1) > 3 )) || { echo "ERROR: You will need more than 3GB of free disk space in $HOME"; exit 1; }
 
 # Check we have internet and DNS
-ping -c3 google.com > /dev/null || { echo "Failed to find internet connection or DNS"; exit 1; }
+ping -c3 google.com > /dev/null || { echo "ERROR: Failed to find internet connection or DNS"; exit 1; }
 
 # Find out where we are
 . /etc/os-release
@@ -23,9 +23,9 @@ echo -e "\nHello ${USER}, you seem to be using ${PRETTY_NAME}\n"
 case $ID in
     mageia)
     echo "Enter the root password to install some initially needed dependencies"
-    su -c "urpmi --no-recommends git cmake wxGTK3-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel alsa-lib-devel \
-           libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-devel hamlib-utils" \
-           || { echo "Deps install failed - try again later"; exit 1; }
+    su -c "urpmi git cmake wxGTK3-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel alsa-lib-devel \
+           libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-devel hamlib-utils python3 python3-devel \
+           libsioclient-devel python3" || { echo "Deps install failed - try again later"; exit 1; }
     ;;
     linuxmint)
     echo "Enter the root password to install some initially needed dependencies"
@@ -83,63 +83,66 @@ case $ID in
 esac
 
 # Create a base working directory in home
-mkdir -p $builddir || { echo "mkdir $builddir failed"; exit 1; }
+mkdir -p $builddir || { echo "ERROR: mkdir $builddir failed"; exit 1; }
 
 # Move into base dir
-cd $builddir || { echo "cd to $builddir failed"; exit 1; }
+cd $builddir || { echo "ERROR: cd to $builddir failed"; exit 1; }
 
 # Delete freedv-gui directory
-rm -rf ${builddir}/freedv-gui || { echo "Error: removing old freedv-gui dir"; exit 1; }
+rm -rf ${builddir}/freedv-gui || { echo "ERROR: removing old freedv-gui dir"; exit 1; }
 
 # Get the latest freedv sources from github
 echo Cloning freedv github repository...
-git clone https://github.com/drowe67/freedv-gui.git || { echo "git clone failed"; exit 1; }
+git clone https://github.com/drowe67/freedv-gui.git || { echo "ERROR: git clone failed"; exit 1; }
 
 # Move into source code directory
-cd ${builddir}/freedv-gui || { echo "cd to freedv-gui failed"; exit 1; }
+cd ${builddir}/freedv-gui || { echo "ERROR: cd to freedv-gui failed"; exit 1; }
 
 # Change to the RADE branch
-git checkout v2.0-dev || { echo "checkout v2.0 failed"; exit 1; }
+git switch v2.0-dev || { echo "ERROR: switch to v2.0-dev branch failed"; exit 1; }
 
 # Create a python virtual environment with access to system python modules
-if [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]] || [[ $ID == "ubuntu" ]] || [[ $ID == "debian" ]] || [[ $ID = "pclinuxos" ]]; then
-    python3 -m venv rade-venv --system-site-packages || { echo "create venv failed"; exit 1; }
+if [[ $ID == "debug" ]] || [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]] || [[ $ID == "ubuntu" ]] || [[ $ID == "debian" ]] || [[ $ID = "pclinuxos" ]]; then
+    python3 -m venv rade-venv --system-site-packages || { echo "ERROR: create venv failed"; exit 1; }
 else
 # Exclude system modules
-    python3 -m venv rade-venv || { echo "create venv failed"; exit 1; }
+    python3 -m venv rade-venv || { echo "ERROR: create venv failed"; exit 1; }
 fi
 
 # Activate it
-. ./rade-venv/bin/activate || { echo "activate venv failed"; exit 1; }
+. ./rade-venv/bin/activate || { echo "ERROR: activate venv failed"; exit 1; }
 
 # Clear cache in venv
 pip cache purge
+pip install --upgrade pip || echo "WARNING: pip upgrade failed"
 
 # Install some python dependencies using pip
 if [[ $ID != "fedora" ]]; then
 pip3 install torch torchaudio --index-url https://download.pytorch.org/whl/cpu || { echo "torch pip install failed"; exit 1; }
 fi
-pip3 install matplotlib || { echo "matplotlib pip install failed"; exit 1; }
-if [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]] || [[ $ID == "ubuntu" ]] || [[ $ID == "debian" ]]; then
-pip3 install NumPy || { echo "numpy pip install failed"; exit 1; }
+
+pip3 install matplotlib || { echo "ERROR: matplotlib pip install failed"; exit 1; }
+
+if [[ $ID == "mageia" ]] || [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]] || [[ $ID == "ubuntu" ]] || [[ $ID == "debian" ]]; then
+pip3 install NumPy || { echo "ERROR: numpy pip install failed"; exit 1; }
 fi
 # Run the freedv build script
-./build_linux.sh || { echo "Build failed for some reason, check for errors above and run again later if a download failed"; deactivate; exit 1; }
-
-# Deactivate venv
-deactivate
+./build_linux.sh || { echo "ERROR: Build failed for some reason, check for errors above and run again later if a download failed"; deactivate; exit 1; }
 
 # Move back into the build directory
-cd ${builddir}/freedv-gui/build_linux || { echo "cd $builddir/freedv-gui/build_linux failed"; exit 1; }
+cd ${builddir}/freedv-gui/build_linux || { echo "ERROR: cd $builddir/freedv-gui/build_linux failed"; exit 1; }
 
 # Create symlink 
 ln -s "$(pwd)"/rade_src/model19_check3 model19_check3 || { echo "Failed to create symlink"; exit 1; }
 
+# Deactivate venv
+deactivate || echo "WARNING:Issue deactivating venv"
+
 # Make start script
-~/freedv-rade-build/mk-start  || echo "WARNING: 'freedv-start' script was not created (maybe exists?)"
+~/freedv-rade-build/mk-start || echo "WARNING: freedv-start script was not created (maybe exists?)"
 
 # Make destop file
-~/freedv-rade-build/mk-desktop || echo "WARNING: Desktop file was not created (maybe exists?)"
+~/freedv-rade-build/mk-desktop || echo "WARNING: freedv desktop file was not created (maybe exists?)"
 
 # Make Update desktop file
 ~/freedv-rade-build/mk-updt-desktop || echo "WARNING: Update-RADE desktop file was not created (maybe exists?)"
diff --git a/mk-desktop b/mk-desktop
--- a/mk-desktop
+++ b/mk-desktop
@@ -21,9 +21,7 @@ X-Desktop-File-Install-Version=0.26
 
 EOF
 
-    chmod +x Desktop/freedv-rade.desktop
-
-    { echo -e "\nDesktop file created!"; exit 0; }
-else
-    { echo -e "\nDesktop file already exists!"; exit 1; } 
+	if [[ -f ~/Desktop/freedv-rade.desktop ]]; then
+    	chmod +x Desktop/freedv-rade.desktop || echo "WARNING: failed to chmod desktop file"
+	fi
 fi
diff --git a/mk-start b/mk-start
--- a/mk-start
+++ b/mk-start
@@ -6,9 +6,9 @@ builddir=/home/$USER/freedv-rade
 
 cd
 # Create start script in user's home if not present
-if ! [[ -f freedv-start ]]; then
+if ! [[ -f ~/freedv-start ]]; then
 
-cat > freedv-start <<EOF
+cat > ~/freedv-start <<EOF
 #!/bin/bash
 # Start script for freedv rade version
 # Specify a config file to use (optional) default is ~/.freedv
@@ -49,8 +49,7 @@ deactivate
 EOF
 
 # Make start script executable
-chmod +x freedv-start || { echo "chmod +x failed"; exit 1; }
-
-else
-    return 1
+	if [[ -f ~/freedv-start ]]; then
+		chmod +x ~/freedv-start || echo "WARNING: chmod +x freedv-start failed"
+	fi
 fi
