comment out pclinuxos, deactivate venv after use, update README

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -68,13 +68,13 @@ case $ID in
             wxwidgets-gtk3 hamlib alsa-lib libao libsndfile python-virtualenv python-numpy manjaro-pulse gsm" \
             || { echo "Deps install failed - try again later"; exit 1; }
     ;;
-    pclinuxos)
-    echo "Enter the root password to install some initially needed dependencies"
-    su -c "apt install automake autoconf libtool git cmake wxgtku3.2-devel libsamplerate-devel libsndfile-devel \
-           speexdsp-devel alsa-lib-devel libao-devel gsm-devel gcc-c++ sox python3 \
-           python3-devel pulseaudio-devel hamlib-devel hamlib-utils" \
-           || { echo "Deps install failed - try again later"; exit 1; }
-    ;;
+#    pclinuxos)  # Hamlib package seems unmaintained here and build from git currently fails.
+#    echo "Enter the root password to install some initially needed dependencies"
+#    su -c "apt install automake autoconf libtool git cmake wxgtku3.2-devel libsamplerate-devel libsndfile-devel \
+#           speexdsp-devel alsa-lib-devel libao-devel gsm-devel gcc-c++ sox python3 \
+#           python3-devel pulseaudio-devel" \
+#           || { echo "Deps install failed - try again later"; exit 1; }
+#    ;;
     *)
     echo "Sorry I don't have packaging information for $PRETTY_NAME yet."
     echo "Please create an issue with details of your system."
@@ -168,7 +168,7 @@ ln -s "$(pwd)"/rade_src/model19_check3 model19_check3 || { echo "Failed to creat
 
 echo -e "\n########### Build is complete \o/ ############\nYou can run it from your home folder using:\n \
       ./freedv-start [-f configfile]"
-      
+
 # Return home
 cd
 
