Change some deps for mint-21.3

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -62,15 +62,16 @@ case $ID in
     ;;
     linuxmint)
     echo "Enter the root password to install some initially needed dependencies"
-    if (( VERSION_ID < 22 )); then
-            sudo apt install libspeexdsp-dev libsamplerate0-dev sox git libwxgtk3.0-dev libhamlib-dev libasound2-dev libao-dev \
-            libgsm1-dev libsndfile1-dev cmake module-assistant build-essential python3.12-venv libpulse-dev autoconf libtool \
-            python3-numpy-dev python3 python3-dev libhamlib-utils fonts-noto-color-emoji \
-            || { echo "Deps install failed - try again later"; exit 1; }
-	else
+    MINT_ID=$(echo $VERSION_ID|tr -d '.')
+    if (( MINT_ID == 22 )); then
             sudo apt install libspeexdsp-dev libsamplerate0-dev sox git libwxgtk3.2-dev libhamlib-dev libasound2-dev libao-dev \
             libgsm1-dev libsndfile1-dev cmake module-assistant build-essential python3.12-venv libpulse-dev autoconf libtool \
             python3-numpy-dev python3 python3-dev libhamlib-utils fonts-noto-color-emoji \
+            || { echo "Deps install failed - try again later"; exit 1; }
+	elif (( MINT_ID == 213 )); then
+            sudo apt install libspeexdsp-dev libsamplerate0-dev sox git libwxgtk3.0-gtk3-dev libhamlib-dev libasound2-dev libao-dev \
+            libgsm1-dev libsndfile1-dev cmake module-assistant build-essential python3.10-venv libpulse-dev autoconf libtool \
+            python3-numpy python3 python3-dev libhamlib-utils fonts-noto-color-emoji \
             || { echo "Deps install failed - try again later"; exit 1; }
 	fi
     ;;
