no recommends in mint and ubuntu with both covering sub-releases

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -26,7 +26,7 @@ rm -f ${basedir}/test_for_perms
 builddir=freedv-rade
 
 # Check we have space
-(( $(df -hBG --output=avail $basedir |tr '\n' ' '|tr -s ' '|xargs|cut -d ' ' -f2|cut -dG -f1) > 3 )) || { echo "ERROR: You will need more than 3GB of free disk space in $basedir"; exit 1; }
+#(( $(df -hBG --output=avail $basedir |tr '\n' ' '|tr -s ' '|xargs|cut -d ' ' -f2|cut -dG -f1) > 3 )) || { echo "ERROR: You will need more than 3GB of free disk space in $basedir"; exit 1; }
 
 # Check we have internet and DNS
 ping -c3 google.com > /dev/null || { echo "ERROR: Failed to find internet connection or DNS"; exit 1; }
@@ -64,12 +64,12 @@ case $ID in
     echo "Enter the root password to install some initially needed dependencies"
     MINT_ID=$(echo $VERSION_ID|cut -d. -f1)
     if (( MINT_ID == 22 )); then
-            sudo apt install --no-install-recommends libspeexdsp-dev libsamplerate0-dev sox git libwxgtk3.2-dev libhamlib-dev \
+            sudo apt install -y --no-install-recommends libspeexdsp-dev libsamplerate0-dev sox git libwxgtk3.2-dev libhamlib-dev \
             libasound2-dev libao-dev libgsm1-dev libsndfile1-dev cmake module-assistant build-essential python3-venv libpulse-dev \
             autoconf libtool python3-numpy-dev python3 python3-dev libhamlib-utils fonts-noto-color-emoji \
             || { echo "Deps install failed - try again later"; exit 1; }
 	elif (( MINT_ID == 21 )); then
-            sudo apt install --no-install-recommends libspeexdsp-dev libsamplerate0-dev sox git libwxgtk3.0-gtk3-dev libhamlib-dev \
+            sudo apt install -y --no-install-recommends libspeexdsp-dev libsamplerate0-dev sox git libwxgtk3.0-gtk3-dev libhamlib-dev \
             libasound2-dev libao-dev libgsm1-dev libsndfile1-dev cmake module-assistant build-essential python3-venv libpulse-dev \
             autoconf libtool python3-numpy python3 python3-dev libhamlib-utils fonts-noto-color-emoji \
             || { echo "Deps install failed - try again later"; exit 1; }
@@ -97,11 +97,11 @@ case $ID in
         UBUNTU_ID=$(echo $VERSION_ID|tr -d '.')
             sudo apt update
         if (( UBUNTU_ID >= 2404 )); then
-            sudo apt install -y libwxgtk3.2-dev python3-numpy-dev python3-venv libspeexdsp-dev libsamplerate0-dev sox git libhamlib-dev \
+            sudo apt install -y --no-install-recommends libwxgtk3.2-dev python3-numpy-dev python3-venv libspeexdsp-dev libsamplerate0-dev sox git libhamlib-dev \
             libao-dev libasound2-dev libgsm1-dev libsndfile1-dev cmake module-assistant build-essential libpulse-dev autoconf libtool \
             python3 python3-dev libhamlib-utils fonts-noto-color-emoji || { echo "Deps install failed - try again later"; exit 1; }
         else
-            sudo apt install -y libwxgtk3.0-gtk3-dev python3-numpy python3-venv libspeexdsp-dev libsamplerate0-dev sox git libhamlib-dev \
+            sudo apt install -y --no-install-recommends libwxgtk3.0-gtk3-dev python3-numpy python3-venv libspeexdsp-dev libsamplerate0-dev sox git libhamlib-dev \
             libasound2-dev libao-dev libgsm1-dev libsndfile1-dev cmake module-assistant build-essential libpulse-dev autoconf libtool \
             python3 python3-dev libhamlib-utils fonts-noto-color-emoji || { echo "Deps install failed - try again later"; exit 1; }
         fi
