update freedv-rade-update script to use basedir

diff --git a/freedv-rade-update b/freedv-rade-update
--- a/freedv-rade-update
+++ b/freedv-rade-update
@@ -7,6 +7,13 @@ prbranch=""
 pname=""
 cname=""
 
+# Get path of base dir in use, defaults to /home/$USER
+if cat /home/${USER}/.freedv-rade-build.cfg |grep -v '^[#]'|grep -q "basedir="; then
+    basedir=$(cat /home/${USER}/.freedv-rade-build.cfg|grep -v '^[#]'|grep 'basedir='|cut -d= -f2)
+else
+    basedir=/home/$USER
+fi
+
 confirm() {
 params=( "$@" )
 rval=7
@@ -25,7 +32,7 @@ while (( $rval > 6 )); do
             [${params[3]}])
                 rval=1
                 ;;
-	        [${params[4]}])
+            [${params[4]}])
                 rval=2
                 ;;
             [${params[5]}])
@@ -49,7 +56,7 @@ done
 }
 
 fastupdt() {
-cd freedv-rade/freedv-gui || exit 1
+cd ${basedir}/freedv-rade/freedv-gui || exit 1
 git switch master || { echo "ERROR: switching to master"; exit 1; }
 git pull
     if (( ${#prbranch} > 0 )); then
@@ -63,7 +70,7 @@ git pull
 
 # Apply a patch if there is one
 if (( ${#pname} > 0 )); then
-    if ! patch -p1 < ../../freedv-rade-build/$pname; then
+    if ! patch -p1 < /home/${USER}/freedv-rade-build/$pname; then
     echo $(pwd)
         echo "Patch failed to apply.  pwd= $(pwd)"
         exit 1
@@ -72,10 +79,10 @@ fi
 
 # Use a specific commit
 if (( ${#cname} > 0 )); then
-	if ! git checkout --detach $cname; then
-		echo "ERROR: Can't find that git#"
-		exit 1
-	fi
+    if ! git checkout --detach $cname; then
+        echo "ERROR: Can't find that git#"
+        exit 1
+    fi
 fi
 
 source ./rade-venv/bin/activate
@@ -103,7 +110,7 @@ echo "Wait a moment..."
 # Check we have internet and DNS
 ping -c3 google.com > /dev/null || { echo "ERROR: Failed to find internet connection or DNS"; exit 1; }
 
-# Do all from user's home folder
+# Do all from user's home folder even if base dir is elsewhere
 cd || exit 1
 
 # Check that freedv-rade-build is there
@@ -127,7 +134,7 @@ echo -e "It will optionally:\n \
 TIP: Hitting ENTER without typing will automatically select the first option to questions."
 
 # Check if there is already a backup and flag it
-[[ -d freedv-rade_bak ]] && bak=1
+[[ -d ${basedir}/freedv-rade_bak ]] && bak=1
 
 if (( bak == 1 )); then
     confirm "\nDo you want to (U)pdate, (F)ull re-build, (B)ackup, (R)estore from backup, (S)witch backup/current, Create (D)esktop launcher or (Q)uit?" "[U/F/B/R/S/D/Q]" "Uu" "Ff" "Bb" "Rr" "Ss" "Dd" "Qq"
@@ -192,7 +199,7 @@ if (( fastupdt == 1 )) && confirm "\n\nUse a specific commit?" "[N/y]" "yY" "nN"
 fi
 
 # Check patch exists
-#(( ${#pname} == 0 )) || [[ -z ../../freedv-rade-build/$pname ]] && { echo "ERROR: Non existant or invalid patch name"; exit 1 }
+(( ${#pname} > 0 )) && [[ -z /home/$USER/freedv-rade-build/$pname ]] && { echo "ERROR: Non existant or invalid patch name"; exit 1 }
 
 
 if ( (( fastupdt == 1 )) || (( update == 1 )) || (( backup = 1 )) ) && (( desktop != 1 )) && (( bak != 1 )) && (( restore != 1 )) && (( switch != 1 )); then
@@ -201,7 +208,7 @@ if ( (( fastupdt == 1 )) || (( update == 1 )) || (( backup = 1 )) ) && (( deskto
     if confirm "\nCreate a backup of the current version?" "[N/y]" "Yy" "Nn"; then
          backup=1
         # Check we have space
-        (( $(df -hBG --output=avail /home |tr '\n' ' '|tr -s ' '|cut -d ' ' -f2|cut -dG -f1) > 3 )) || { echo -e "\nInsufficient disk space for backup"; backup=0; }
+        (( $(df -hBG --output=avail $basedir |tr '\n' ' '|tr -s ' '|cut -d ' ' -f2|cut -dG -f1) > 3 )) || { echo -e "\nInsufficient disk space for backup"; backup=0; }
     fi
 fi
 if (( bak == 1 )) && (( restore != 1 )) && (( desktop != 1 )) && (( switch != 1 )); then
@@ -267,8 +274,8 @@ if (( fastupdt == 1 )) || (( update == 1 )) || (( backup == 1 )) || (( restore =
 # Create backup
         if (( backup == 1)); then
             echo -e "\nCreating backup..."
-            rm -rf freedv-rade_bak/
-            if cp -rf freedv-rade/ freedv-rade_bak; then
+            rm -rf ${basedir}/freedv-rade_bak/
+            if cp -rf ${basedir}/freedv-rade/ ${basedir}/freedv-rade_bak; then
                 echo "Backup complete."
             else
                 echo "Backup failed."
@@ -291,7 +298,7 @@ if (( fastupdt == 1 )) || (( update == 1 )) || (( backup == 1 )) || (( restore =
 # Restore from backup
         if (( restore == 1 )); then
             echo -e "\nRestoring from backup..."
-            if (rm -rf freedv-rade/ && cp -rf freedv-rade_bak/ freedv-rade); then
+            if (rm -rf ${basedir}/freedv-rade/ && cp -rf ${basedir}/freedv-rade_bak/ ${basedir}/freedv-rade); then
                 echo "Restore complete."
             else
                 echo "Restore failed."
@@ -301,11 +308,11 @@ if (( fastupdt == 1 )) || (( update == 1 )) || (( backup == 1 )) || (( restore =
 # Switch backup with current
 		if (( switch == 1 )); then
 			echo -e "\nSwitching backup with current..."
-			[[ -d freedv-rade_tmp ]] && rm -fr freedv-rade_tmp
+			[[ -d ${basedir}/freedv-rade_tmp ]] && rm -fr ${basedir}/freedv-rade_tmp
 
-			mv freedv-rade freedv-rade_tmp || { echo "Failed to move freedv-rade to freedv-rade_tmp"; exit 1; }
-			mv freedv-rade_bak freedv-rade || { echo "Failed to move freedv-rade_bak to freedv-rade"; exit 1; }
-			mv freedv-rade_tmp freedv-rade_bak ||{ echo "Failed to move freedv-rade_tmp to freedv-rade_bak"; exit 1; }
+			mv ${basedir}/freedv-rade ${basedir}/freedv-rade_tmp || { echo "Failed to move freedv-rade to freedv-rade_tmp"; exit 1; }
+			mv ${basedir}/freedv-rade_bak ${basedir}/freedv-rade || { echo "Failed to move freedv-rade_bak to freedv-rade"; exit 1; }
+			mv ${basedir}/freedv-rade_tmp ${basedir}/freedv-rade_bak ||{ echo "Failed to move freedv-rade_tmp to freedv-rade_bak"; exit 1; }
 			echo -e "\nDone :)\n"
 		fi
 
