use dnf or dnf5 in fedora according to version

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -40,9 +40,8 @@ echo -e "Installation will be made into ${basedir}/${builddir}\n"
 case $ID in
     mageia)
     # Check Mageia version as google emoji fonts package changed name.
-    mgaver=$(cat /etc/mageia-release|cut -d' ' -f3)
     echo "Enter the root password to install some initially needed dependencies"
-    if [[ $mgaver -gt "9" ]]; then
+    if [[ "$VERSION_ID" -ge "9" ]]; then
             su -c "urpmi git cmake wxGTK3-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel alsa-lib-devel \
             libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-devel hamlib-utils python3 python3-devel \
             fonts-ttf-google-noto-emoji-color" \
@@ -70,11 +69,19 @@ case $ID in
     ;;
     fedora)
     echo "Enter the root password to install some initially needed dependencies"
-    sudo dnf group install development-tools
-    sudo dnf install --setopt=install_weak_deps=False git cmake wxGTK-devel libsamplerate-devel libsndfile-devel speexdsp-devel \
-    hamlib-devel hamlib alsa-lib-devel libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-libs-devel libtool \
-         python3-torchaudio python3-torch python3-devel google-noto-emoji-color-fonts \
-           || { echo "Deps install failed - try again later"; exit 1; }
+        if [[ "$VERSION_ID" => "42" ]]; then
+            sudo dnf5 install @development-tools
+            sudo dnf5 install git cmake wxGTK-devel libsamplerate-devel libsndfile-devel speexdsp-devel \
+            hamlib-devel hamlib alsa-lib-devel libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-libs-devel libtool \
+            python3-torchaudio python3-torch python3-devel google-noto-emoji-color-fonts --no-weakdeps \
+            || { echo "Deps install failed - try again later"; exit 1; }
+        elif [[ "$VERSION_ID" =< "41" ]]; then
+            sudo dnf group install development-tools
+            sudo dnf install --setopt=install_weak_deps=False git cmake wxGTK-devel libsamplerate-devel libsndfile-devel speexdsp-devel \
+            hamlib-devel hamlib alsa-lib-devel libao-devel gsm-devel gcc-c++ sox python3-virtualenv pulseaudio-libs-devel libtool \
+            python3-devel google-noto-emoji-color-fonts \
+            || { echo "Deps install failed - try again later"; exit 1; }
+        fi
     ;;
     ubuntu)
     echo "Enter the root password to install some initially needed dependencies"
@@ -110,7 +117,7 @@ case $ID in
 #           || { echo "Deps install failed - try again later"; exit 1; }
 #    ;;
     *)
-    echo "Sorry I don't have packaging information for $PRETTY_NAME yet."
+    echo "Sorry I don't have information for $PRETTY_NAME yet."
     echo "Please create an issue with details of your system."
     exit 0
     ;;
@@ -151,9 +158,7 @@ pip cache purge
 pip install --upgrade pip || echo "WARNING: pip upgrade failed"
 
 # Install some python dependencies using pip
-if [[ $ID != "fedora" ]]; then
 pip3 install torch torchaudio --index-url https://download.pytorch.org/whl/cpu || { echo "torch pip install failed"; exit 1; }
-fi
 
 pip3 install matplotlib || { echo "ERROR: matplotlib pip install failed"; exit 1; }
 
