- add auto groups to all distros - use --auto --no-recommends with Mageia

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -91,6 +91,18 @@ run_as_root() {
     return 1
 }
 
+groups_add() {
+# Add the user to each group, if not already a member
+for group in "${groups_to_add[@]}"; do
+    if id "$user" | grep -qw "$group"; then
+        echo "User $user is already in group $group"
+    else
+        echo "Adding $user to group $group"
+        run_as_root "usermod -aG $group $user"
+    fi
+done
+}
+
 groups_to_add=()
 
 # Install some system deps
@@ -102,8 +114,9 @@ case $ID in
     if (( MGA_ID > 9 )); then
             run_as_root "urpmi git cmake wxGTK3-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel alsa-lib-devel \
             libao-devel gsm-devel gcc-c++ automake sox python3-virtualenv pulseaudio-devel hamlib-utils python3 python3-devel \
-            fonts-ttf-google-noto-emoji-color" \
-            || { echo "Deps install failed"; exit 1; }
+            fonts-ttf-google-noto-emoji-color" || { echo "Deps install failed"; exit 1; }
+
+            groups_add || { echo "Group add failed"; exit 1; }
     else
             run_as_root "
             urpmi git cmake wxGTK3-devel libsamplerate-devel libsndfile-devel speexdsp-devel hamlib-devel alsa-lib-devel \
