Apply changes for v2.0.0

diff --git a/freedv-rade-build b/freedv-rade-build
--- a/freedv-rade-build
+++ b/freedv-rade-build
@@ -1,5 +1,5 @@
 #!/bin/bash
-# This script tries to install the pre-release freedv-v2.00 from github on various linux distributions
+# This script installs freedv RADE from github on various linux distributions
 # Check we are not root
 ((UID)) || { echo "ERROR: You must NOT run $0 as root - aborting!"; exit 0; }
 
@@ -139,8 +139,8 @@ git clone https://github.com/drowe67/freedv-gui.git || { echo "ERROR: git clone 
 # Move into source code directory
 cd ${basedir}/${builddir}/freedv-gui || { echo "ERROR: cd to freedv-gui failed"; exit 1; }
 
-# Change to the RADE branch
-git switch v2.0-dev || { echo "ERROR: switch to v2.0-dev branch failed"; exit 1; }
+# Change to the dev branch when available
+#git switch v2.0.0 || { echo "ERROR: switch to v2.0-dev branch failed"; exit 1; }
 
 # Create a python virtual environment with access to system python modules
 if [[ $ID == "debug" ]] || [[ $ID == "linuxmint" ]] || [[ $ID == "fedora" ]] || [[ $ID == "ubuntu" ]] || [[ $ID == "debian" ]] || [[ $ID = "pclinuxos" ]]; then
diff --git a/freedv-rade-update b/freedv-rade-update
--- a/freedv-rade-update
+++ b/freedv-rade-update
@@ -2,7 +2,7 @@
 #set -x
 
 # Set default branch
-default="v2.0-dev"
+default="master"
 prbranch=""
 pname=""
 cname=""
@@ -61,7 +61,7 @@ cd ${basedir}/freedv-rade/freedv-gui || exit 1
 # Remove any patched/edited files
 git reset --hard
 
-git switch master || { echo "ERROR: switching to master"; exit 1; }
+git switch $default || { echo "ERROR: switching to $default"; exit 1; }
 
 git pull
 
@@ -123,7 +123,7 @@ cd || exit 1
 # Preamble
 clear
 echo "################## Welcome to freedv-rade-update ######################"
-echo -e "\n This script is for maintaining a build of FreeDV RADE development version\n \
+echo -e "\n This script is for maintaining a build of FreeDV RADE \n \
 created using freedv-rade-build script.\n"
 echo -e "It will optionally:\n \
 * Update FreeDV to the latest $default or a specified branch (fast, recommended) \n \
