- Use correct Desktop dir name across locales - Add locale output to log - report when .desktop files are created

diff --git a/mk-desktop b/mk-desktop
--- a/mk-desktop
+++ b/mk-desktop
@@ -5,8 +5,8 @@
 ((UID)) || { echo "You must NOT run $0 as root - aborting!"; exit 0; }
 
 # Create .desktop file only if missing (don't overwrite existing)
-if ! [[ -f ~/Desktop/freedv-rade.desktop ]]; then
-cat > ~/Desktop/freedv-rade.desktop <<EOF
+if ! [[ -f $(xdg-user-dir DESKTOP)/freedv-rade.desktop ]]; then
+cat > $(xdg-user-dir DESKTOP)/freedv-rade.desktop <<EOF
 [Desktop Entry]
 Version=1.0
 Name=FreeDV-RADE
@@ -21,7 +21,8 @@ X-Desktop-File-Install-Version=0.26
 
 EOF
 
-	if [[ -f ~/Desktop/freedv-rade.desktop ]]; then
-    	chmod +x ~/Desktop/freedv-rade.desktop || echo "WARNING: failed to chmod desktop file"
+    if [[ -f $(xdg-user-dir DESKTOP)/freedv-rade.desktop ]]; then
+        chmod +x $(xdg-user-dir DESKTOP)/freedv-rade.desktop || echo "WARNING: failed to chmod desktop file"
+        echo "FreeDV-RADE Desktop file created"
 	fi
 fi
